variables:
  CI_TOOL: gitlab-ci
  APT_DEPENDENCIES: "libtinyxml2-dev libboost-all-dev libjsoncpp-dev libgeos++-dev libgeos-dev qhull-bin libqhull-dev libltdl-dev libspacevecalg-dev libeigen-qld-dev libsch-core-dev librbdyn-dev hrpsys-base liblapack-dev libblas-dev libjpeg-dev libpng12-dev"
  GIT_DEPENDENCIES: "git@gite.lirmm.fr:multi-contact/eigen-lssol.git jrl-umi3218/Tasks git@gite.lirmm.fr:multi-contact/mc_rbdyn_urdf_cpp.git nanomsg/nanomsg git@gite.lirmm.fr:multi-contact/mc_rtc_ros_data git@gite.lirmm.fr:multi-contact/mc_rtc"
  MASTER_PPA: "pierre-gergondet+ppa/multi-contact-unstable hrg/daily"
  CMAKE_ADDITIONAL_OPTIONS: "-DPYTHON_BINDING=OFF"

before_script:
  - wget -q https://cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.sh
  - chmod +x cmake-3.5.1-Linux-x86_64.sh
  - ./cmake-3.5.1-Linux-x86_64.sh --prefix=/usr --skip-license
  - git submodule update --quiet --init --recursive
  - ./.jrl-ci/dependencies/eigen-3.2

clang-format:
  stage: clang-format
  before_script: []
  script:
    - ./.clang-format-check.sh
  tags:
    - clang-format

build_it:
  stage: build
  script:
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

stages:
  - clang-format
  - build
