variables:
  CI_TOOL: gitlab-ci
  APT_DEPENDENCIES: "libtinyxml2-dev libboost-all-dev libgeos++-dev libgeos-dev libltdl-dev libtasks-qld-dev hrpsys-base liblapack-dev libblas-dev libjpeg-dev libpng12-dev libmc-rbdyn-urdf-dev"
  GIT_DEPENDENCIES: "nanomsg/nanomsg git@gite.lirmm.fr:multi-contact/mc_rtc_ros_data git@gite.lirmm.fr:multi-contact/mc_rtc"
  MASTER_PPA: "hrg/daily"
  CMAKE_ADDITIONAL_OPTIONS: "-DPYTHON_BINDING=OFF"
  # No test in this package
  ALLOW_TESTSUITE_FAILURE: "true"

before_script:
  - git submodule update --quiet --init --recursive
  - add-apt-repository ppa:pierre-gergondet+ppa/multi-contact-unstable && apt-get update && apt-get upgrade cmake libeigen3-dev -qq

clang-format:
  stage: clang-format
  before_script: []
  script:
    - ./.clang-format-check.sh
  tags:
    - clang-format

build_it:
  stage: build
  script:
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

stages:
  - clang-format
  - build
